apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: hybris-controller-manager
  name: hybris-controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: hybris-controller-manager
