# permissions for end users to edit hybrisbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hybrisbase-editor-role
rules:
- apiGroups:
  - hybris.hybris.org
  resources:
  - hybrisbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hybris.hybris.org
  resources:
  - hybrisbases/status
  verbs:
  - get
