# permissions for end users to view hybrisapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hybrisapp-viewer-role
rules:
- apiGroups:
  - hybris.hybris.org
  resources:
  - hybrisapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hybris.hybris.org
  resources:
  - hybrisapps/status
  verbs:
  - get
