# permissions for end users to view hybrisbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hybrisbase-viewer-role
rules:
- apiGroups:
  - hybris.hybris.org
  resources:
  - hybrisbases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hybris.hybris.org
  resources:
  - hybrisbases/status
  verbs:
  - get
